GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/62d81ca858ea0a4cda40d210

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "nodeBlog"
}

###

POST https://susbcriber-rest-api-node-js.herokuapp.com/subscribers


{
    "name": "Amazing Person",
    "subscribedToChannel": "nodeBlog"
}

###

DELETE http://localhost:3000/subscribers/62d82283e3fbe846899e6681

###

PATCH http://localhost:3000/subscribers/62d8219f43f10e3baed1f76e
Content-Type: application/json

{
    "name": "New Person"
}